### ISSUE TITLE
JDBC connector crashes when datetime field is NULL

### ISSUE THREAD

**Issue by liu-xiao-guo** [Vantiq/vantiq-extension-sources#143]
I have a database like the following:
![database](https://user-images.githubusercontent.com/8455957/53804457-84ee0300-3f82-11e9-8753-04ba694aa2c0.png)

The datetime field is not a compulsory field for the database. Once I get it running, it crashes the JDBC connector with the following error:

der - Map of the received message: {op=configureExtension, resourceName=sources, isSystemResource=true, resourceId=SapOrder, parameters={}, object={mapId=b7a930aa-c681-478e-8fe7-4dae76b200fd, config={jdbcConfig={general={dbURL=jdbc:mysql://localhost:3306/xugong?useSSL=false&serverTimezone=UTC, password=1234, pollQuery=SELECT * FROM test_table, pollTime=3000, username=root}}, vantiq={packageRows=true}}}, sessionId=bb865875b0dd26a7b25822f63c605790, contentType=application/json, skipMonitoring=false, isExternal=false, address=673d6f32-8b96-4a8b-b6b8-2c038a1cabe4, messageHeaders={}}
20:02:57.902 [OkHttp https://dev.vantiq.cn/...] INFO  io.vantiq.extjsdk.ExtensionWebSocketListener#SapOrder - Successful connection to SapOrder
Exception in thread "executePolling" java.lang.NullPointerException
        at java.util.Calendar.setTime(Calendar.java:1770)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
        at java.text.DateFormat.format(DateFormat.java:345)
        at io.vantiq.extsrc.jdbcSource.JDBC.createMapFromResults(JDBC.java:134)
        at io.vantiq.extsrc.jdbcSource.JDBC.processQuery(JDBC.java:71)
        at io.vantiq.extsrc.jdbcSource.JDBCCore.executePolling(JDBCCore.java:249)
        at io.vantiq.extsrc.jdbcSource.JDBCHandleConfiguration$3.run(JDBCHandleConfiguration.java:195)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

**Comment by liu-xiao-guo** [comment]
@namirfa could you please fix the problem as I am doing a project using JDBC. Also, a developer just spotted this problem when he tried to use SQL server.

Thanks
