### ISSUE TITLE
Increase message size for the JDBC Connector

### ISSUE THREAD

**Issue by msilva123** [Vantiq/vantiq-extension-sources#163]
Can we increase the message size for the JDBC Connector.

I get the following error stating max message size is 262144 (assuming bytes):
 
17:08:30.598 [OkHttp https://dev.vantiq.com/...] ERROR io.vantiq.extjsdk.ExtensionWebSocketListener#JDBC1 - Map of the r
eceived message: {status=500, contentType=application/json, body=[{code=io.vantiq.server.error, message=Cannot process b
inary frame of size 369122, it would cause message buffer (size 0) to overflow max message size of 262144, params=[], de
tails=java.lang.IllegalStateException: Cannot process binary frame of size 369122, it would cause message buffer (size 0
) to overflow max message size of 262144
        at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handleBinaryFrame(WebSocketImplBase.java:371)
        at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handle(WebSocketImplBase.java:323)
        at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handle(WebSocketImplBase.java:309)
        at io.vertx.core.http.impl.WebSocketImplBase.handleFrame(WebSocketImplBase.java:302)
        at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:208)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:141)
        at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:397)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServer
ExtensionHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
}]}
17:08:30.612 [OkHttp https://dev.vantiq.com/...] DEBUG io.vantiq.extjsdk.ExtensionWebSocketListener#JDBC1 - Http respons
e received
17:08:30.616 [OkHttp https://dev.vantiq.com/...] DEBUG io.vantiq.extjsdk.ExtensionWebSocketListener#JDBC1 - Http respons
e received with no handler set
 
The size of the records is not large:
  {
      "id": 774138746,
      "node_sensor_id": "008000000400D449",
      "name": "VALVE_A_STATUS",
      "value": 0,
      "updated_date": "2019-05-10T17:10:43.000-0700",
      "is_active": "Y",
      "created_date": "2019-05-10T17:10:43.000-0700",
      "timestamp": 1557533443
   },

**Comment by fhcarter** [comment]
We're looking at being able to stream over multiple messages.  This should solve your issue, I think.
